using System.Text;
using Helper.Runtime.Core;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Helper.Runtime.Generation;

internal sealed class CompileGateSymbolRecoveryRepairSet
{
    private readonly IUsingInferenceService _usingInference;
    private readonly IMethodBodySemanticGuard _semanticGuard;

    public CompileGateSymbolRecoveryRepairSet(
        IUsingInferenceService usingInference,
        IMethodBodySemanticGuard semanticGuard)
    {
        _usingInference = usingInference;
        _semanticGuard = semanticGuard;
    }

    public async Task<bool> ApplyMissingUsingFixAsync(
        string compileWorkspace,
        IReadOnlyList<BuildError> errors,
        CancellationToken ct)
    {
        var usings = new HashSet<string>(StringComparer.Ordinal);
        foreach (var error in errors.Where(e => string.Equals(CompileGateRepairDiagnostics.ExtractCode(e), "CS0246", StringComparison.Ordinal)))
        {
            foreach (System.Text.RegularExpressions.Match match in CompileGateRepairPatterns.MissingTypeRegex.Matches(error.Message))
            {
                var token = match.Groups["type"].Value;
                var @using = _usingInference.ResolveUsingForTypeToken(token);
                if (!string.IsNullOrWhiteSpace(@using))
                {
                    usings.Add(@using);
                }
            }
        }

        if (usings.Count == 0)
        {
            return false;
        }

        var changed = false;
        foreach (var filePath in CompileGateRepairDiagnostics.EnumerateCodeFiles(compileWorkspace))
        {
            ct.ThrowIfCancellationRequested();
            var source = await File.ReadAllTextAsync(filePath, ct).ConfigureAwait(false);
            var tree = CSharpSyntaxTree.ParseText(source);
            var root = await tree.GetRootAsync(ct).ConfigureAwait(false) as CompilationUnitSyntax;
            if (root is null)
            {
                continue;
            }

            var existing = root.Usings.Select(static u => u.Name?.ToString())
                .Where(static value => !string.IsNullOrWhiteSpace(value))
                .ToHashSet(StringComparer.Ordinal);
            var toInsert = usings
                .Where(u => !existing.Contains(u))
                .OrderBy(u => u, StringComparer.Ordinal)
                .Select(u => SyntaxFactory.UsingDirective(SyntaxFactory.ParseName(u)))
                .ToList();
            if (toInsert.Count == 0)
            {
                continue;
            }

            var updated = root.WithUsings(root.Usings.InsertRange(0, toInsert)).NormalizeWhitespace();
            await File.WriteAllTextAsync(filePath, updated.ToFullString(), ct).ConfigureAwait(false);
            changed = true;
        }

        return changed;
    }

    public async Task<bool> ApplyMissingTypeStubFixAsync(
        string compileWorkspace,
        IReadOnlyList<BuildError> errors,
        CancellationToken ct)
    {
        var missingTypes = new HashSet<string>(StringComparer.Ordinal);
        foreach (var error in errors.Where(e => string.Equals(CompileGateRepairDiagnostics.ExtractCode(e), "CS0246", StringComparison.Ordinal)))
        {
            foreach (System.Text.RegularExpressions.Match match in CompileGateRepairPatterns.MissingTypeRegex.Matches(error.Message))
            {
                var token = CompileGateRepairSyntaxHelpers.NormalizeMissingTypeToken(match.Groups["type"].Value);
                if (string.IsNullOrWhiteSpace(token))
                {
                    continue;
                }

                if (!CompileGateRepairSyntaxHelpers.IsValidIdentifier(token) ||
                    CompileGateRepairPatterns.TypeStubExclusions.Contains(token))
                {
                    continue;
                }

                missingTypes.Add(token);
            }
        }

        if (missingTypes.Count == 0)
        {
            return false;
        }

        var stubPath = Path.Combine(compileWorkspace, "CompileGateTypeStubs.g.cs");
        var allTypeStubs = new HashSet<string>(StringComparer.Ordinal);
        if (File.Exists(stubPath))
        {
            var current = await File.ReadAllTextAsync(stubPath, ct).ConfigureAwait(false);
            foreach (System.Text.RegularExpressions.Match match in CompileGateRepairPatterns.ExistingTypeStubRegex.Matches(current))
            {
                var name = match.Groups["name"].Value;
                if (CompileGateRepairSyntaxHelpers.IsValidIdentifier(name))
                {
                    allTypeStubs.Add(name);
                }
            }
        }

        allTypeStubs.UnionWith(missingTypes);
        if (allTypeStubs.Count == 0)
        {
            return false;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        foreach (var typeName in allTypeStubs.OrderBy(static name => name, StringComparer.Ordinal))
        {
            sb.AppendLine(CompileGateRepairSyntaxHelpers.BuildTypeStubDeclaration(typeName));
        }

        var content = sb.ToString();
        if (File.Exists(stubPath))
        {
            var existing = await File.ReadAllTextAsync(stubPath, ct).ConfigureAwait(false);
            if (string.Equals(existing, content, StringComparison.Ordinal))
            {
                return false;
            }
        }

        await File.WriteAllTextAsync(stubPath, content, ct).ConfigureAwait(false);
        return true;
    }

    public async Task<bool> ApplyUnknownSymbolFallbackAsync(
        string compileWorkspace,
        IReadOnlyList<BuildError> errors,
        CancellationToken ct)
    {
        var diagnosticReferences = CompileGateRepairDiagnostics.ResolveDiagnosticReferences(
            compileWorkspace,
            errors,
            CompileGateRepairPatterns.UnknownSymbolCodes);
        if (diagnosticReferences.Count == 0)
        {
            return false;
        }

        var changed = false;
        foreach (var filePath in CompileGateRepairDiagnostics.EnumerateTargetCodeFiles(diagnosticReferences))
        {
            ct.ThrowIfCancellationRequested();
            var source = await File.ReadAllTextAsync(filePath, ct).ConfigureAwait(false);
            var tree = CSharpSyntaxTree.ParseText(source);
            var root = await tree.GetRootAsync(ct).ConfigureAwait(false) as CompilationUnitSyntax;
            if (root is null)
            {
                continue;
            }

            var fileReferences = diagnosticReferences
                .Where(reference => string.Equals(reference.FilePath, filePath, StringComparison.OrdinalIgnoreCase))
                .ToList();
            var suspiciousSymbols = CompileGateRepairSyntaxHelpers.ExtractSuspiciousSymbols(
                fileReferences.Select(static reference => reference.Error).ToArray());
            var targetLines = fileReferences
                .Select(static reference => reference.Line)
                .Where(static line => line > 0)
                .ToHashSet();
            var candidates = root.DescendantNodes()
                .OfType<MethodDeclarationSyntax>()
                .Where(m => m.Parent is not InterfaceDeclarationSyntax)
                .Where(m =>
                    CompileGateRepairSyntaxHelpers.DiagnosticTargetsMethod(m, targetLines) ||
                    CompileGateRepairSyntaxHelpers.MethodContainsAnySymbol(m, suspiciousSymbols))
                .ToList();
            if (candidates.Count == 0)
            {
                continue;
            }

            SyntaxNode updatedRoot = root;
            var fileChanged = false;
            foreach (var method in candidates)
            {
                var signature = method
                    .WithBody(null)
                    .WithExpressionBody(null)
                    .WithSemicolonToken(default)
                    .NormalizeWhitespace()
                    .ToFullString();

                var body = CompileGateRepairSyntaxHelpers.GetMethodBodyText(method);
                var safety = _semanticGuard.Guard(signature, body);
                var shouldFallback = safety.UsedFallback;
                if (!shouldFallback && suspiciousSymbols.Count > 0)
                {
                    shouldFallback = suspiciousSymbols.Any(symbol => body.Contains(symbol, StringComparison.Ordinal));
                }

                if (!shouldFallback)
                {
                    continue;
                }

                var fallbackBody = safety.UsedFallback
                    ? safety.Body
                    : CompileGateRepairSyntaxHelpers.BuildForcedFallbackBody(_semanticGuard, signature);
                var fallbackBlock = CompileGateRepairSyntaxHelpers.ParseBlock(fallbackBody);
                var fixedMethod = method
                    .WithBody(fallbackBlock)
                    .WithExpressionBody(null)
                    .WithSemicolonToken(default);

                updatedRoot = updatedRoot.ReplaceNode(method, fixedMethod);
                fileChanged = true;
            }

            if (!fileChanged)
            {
                continue;
            }

            await File.WriteAllTextAsync(filePath, updatedRoot.NormalizeWhitespace().ToFullString(), ct).ConfigureAwait(false);
            changed = true;
        }

        return changed;
    }
}

