using System.Text;
using System.Xml.Linq;
using Helper.Runtime.Core;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Helper.Runtime.Generation;

internal sealed class CompileGateProjectRepairSet
{
    public async Task<bool> ApplyMissingEntryPointFixAsync(string compileWorkspace, CancellationToken ct)
    {
        var entryPointPath = Path.Combine(compileWorkspace, "CompileGateEntryPoint.g.cs");
        const string entryPointContent = """
// <auto-generated />
public static class CompileGateEntryPoint
{
    [global::System.STAThread]
    public static void Main(string[] args)
    {
    }
}
""";

        if (File.Exists(entryPointPath))
        {
            var existing = await File.ReadAllTextAsync(entryPointPath, ct).ConfigureAwait(false);
            if (string.Equals(existing, entryPointContent, StringComparison.Ordinal))
            {
                return false;
            }
        }

        await File.WriteAllTextAsync(entryPointPath, entryPointContent, Encoding.UTF8, ct).ConfigureAwait(false);
        return true;
    }

    public async Task<bool> ApplyAsyncTaskReturnTypeFixAsync(string compileWorkspace, CancellationToken ct)
    {
        var changed = false;
        foreach (var filePath in CompileGateRepairDiagnostics.EnumerateCodeFiles(compileWorkspace))
        {
            ct.ThrowIfCancellationRequested();
            var source = await File.ReadAllTextAsync(filePath, ct).ConfigureAwait(false);
            var tree = CSharpSyntaxTree.ParseText(source);
            var root = await tree.GetRootAsync(ct).ConfigureAwait(false) as CompilationUnitSyntax;
            if (root is null)
            {
                continue;
            }

            var methods = root.DescendantNodes()
                .OfType<MethodDeclarationSyntax>()
                .Where(m => m.Modifiers.Any(static token => token.IsKind(SyntaxKind.AsyncKeyword)))
                .Where(m => CompileGateRepairSyntaxHelpers.NeedsTaskReturnTypeQualification(m.ReturnType))
                .ToList();
            if (methods.Count == 0)
            {
                continue;
            }

            var replacements = new Dictionary<MethodDeclarationSyntax, MethodDeclarationSyntax>();
            foreach (var method in methods)
            {
                var updatedReturnType = CompileGateRepairSyntaxHelpers.QualifyTaskReturnType(method.ReturnType);
                if (string.Equals(
                        CompileGateRepairSyntaxHelpers.RemoveWhitespace(method.ReturnType.ToString()),
                        CompileGateRepairSyntaxHelpers.RemoveWhitespace(updatedReturnType.ToString()),
                        StringComparison.Ordinal))
                {
                    continue;
                }

                replacements[method] = method.WithReturnType(updatedReturnType);
            }

            if (replacements.Count == 0)
            {
                continue;
            }

            var updatedRoot = root.ReplaceNodes(replacements.Keys, (original, _) => replacements[original]);
            await File.WriteAllTextAsync(filePath, updatedRoot.NormalizeWhitespace().ToFullString(), ct).ConfigureAwait(false);
            changed = true;
        }

        return changed;
    }

    public Task<bool> ApplyMissingPackageReferenceFixAsync(
        string compileWorkspace,
        IReadOnlyList<BuildError> errors,
        CancellationToken ct)
    {
        var tokens = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var error in errors)
        {
            var code = CompileGateRepairDiagnostics.ExtractCode(error);
            if (!string.Equals(code, "CS0246", StringComparison.Ordinal) &&
                !string.Equals(code, "CS0234", StringComparison.Ordinal) &&
                !string.Equals(code, "CS0012", StringComparison.Ordinal))
            {
                continue;
            }

            foreach (System.Text.RegularExpressions.Match match in CompileGateRepairPatterns.MissingTypeRegex.Matches(error.Message))
            {
                var token = match.Groups["type"].Value;
                if (string.IsNullOrWhiteSpace(token))
                {
                    continue;
                }

                tokens.Add(token);
                if (!token.Contains('.'))
                {
                    continue;
                }

                foreach (var segment in token.Split('.', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
                {
                    if (!string.IsNullOrWhiteSpace(segment))
                    {
                        tokens.Add(segment);
                    }
                }
            }
        }

        var referencesToAdd = tokens
            .Select(token => CompileGateRepairPatterns.PackageByToken.TryGetValue(token, out var package) ? package : null)
            .Where(static package => package is not null)
            .Cast<PackageReferenceSpec>()
            .Distinct()
            .ToList();
        if (referencesToAdd.Count == 0)
        {
            return Task.FromResult(false);
        }

        var changed = false;
        foreach (var csproj in Directory.EnumerateFiles(compileWorkspace, "*.csproj", SearchOption.TopDirectoryOnly))
        {
            ct.ThrowIfCancellationRequested();

            XDocument doc;
            try
            {
                doc = XDocument.Load(csproj);
            }
            catch
            {
                continue;
            }

            var root = doc.Root;
            if (root is null)
            {
                continue;
            }

            var ns = root.Name.Namespace;
            var existing = root.Descendants()
                .Where(static x => x.Name.LocalName == "PackageReference")
                .Select(x => x.Attribute("Include")?.Value)
                .Where(static x => !string.IsNullOrWhiteSpace(x))
                .ToHashSet(StringComparer.OrdinalIgnoreCase);

            var itemGroup = root.Elements()
                .FirstOrDefault(x =>
                    x.Name.LocalName == "ItemGroup" &&
                    x.Elements().Any(child => child.Name.LocalName == "PackageReference"));
            if (itemGroup is null)
            {
                itemGroup = new XElement(ns + "ItemGroup");
                root.Add(itemGroup);
            }

            var fileChanged = false;
            foreach (var package in referencesToAdd)
            {
                if (existing.Contains(package.Include))
                {
                    continue;
                }

                var packageRef = new XElement(ns + "PackageReference");
                packageRef.SetAttributeValue("Include", package.Include);
                if (!string.IsNullOrWhiteSpace(package.Version))
                {
                    packageRef.SetAttributeValue("Version", package.Version);
                }

                itemGroup.Add(packageRef);
                existing.Add(package.Include);
                fileChanged = true;
            }

            if (!fileChanged)
            {
                continue;
            }

            doc.Save(csproj);
            changed = true;
        }

        return Task.FromResult(changed);
    }

    public async Task<bool> ApplyInvalidNamespaceUsingFixAsync(
        string compileWorkspace,
        IReadOnlyList<BuildError> errors,
        CancellationToken ct)
    {
        var invalidTypeNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var error in errors.Where(e => string.Equals(CompileGateRepairDiagnostics.ExtractCode(e), "CS0138", StringComparison.Ordinal)))
        {
            var match = CompileGateRepairPatterns.InvalidUsingTypeRegex.Match(error.Message ?? string.Empty);
            if (!match.Success)
            {
                continue;
            }

            var typeName = match.Groups["type"].Value.Trim();
            if (string.IsNullOrWhiteSpace(typeName))
            {
                continue;
            }

            invalidTypeNames.Add(typeName);
            var simpleName = typeName.Split('.', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).LastOrDefault();
            if (!string.IsNullOrWhiteSpace(simpleName))
            {
                invalidTypeNames.Add(simpleName);
            }
        }

        if (invalidTypeNames.Count == 0)
        {
            return false;
        }

        var changed = false;
        foreach (var filePath in CompileGateRepairDiagnostics.EnumerateCodeFiles(compileWorkspace))
        {
            ct.ThrowIfCancellationRequested();
            var source = await File.ReadAllTextAsync(filePath, ct).ConfigureAwait(false);
            var tree = CSharpSyntaxTree.ParseText(source);
            var root = await tree.GetRootAsync(ct).ConfigureAwait(false) as CompilationUnitSyntax;
            if (root is null || root.Usings.Count == 0)
            {
                continue;
            }

            var usingsToRemove = root.Usings
                .Where(u => u.Alias is null && !u.StaticKeyword.IsKind(SyntaxKind.StaticKeyword))
                .Where(u =>
                {
                    var usingName = u.Name?.ToString();
                    if (string.IsNullOrWhiteSpace(usingName))
                    {
                        return false;
                    }

                    if (invalidTypeNames.Contains(usingName))
                    {
                        return true;
                    }

                    var simpleName = usingName.Split('.', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).LastOrDefault();
                    return !string.IsNullOrWhiteSpace(simpleName) && invalidTypeNames.Contains(simpleName);
                })
                .ToList();
            if (usingsToRemove.Count == 0)
            {
                continue;
            }

            var updatedRoot = root.RemoveNodes(usingsToRemove, SyntaxRemoveOptions.KeepNoTrivia) as CompilationUnitSyntax;
            if (updatedRoot is null)
            {
                continue;
            }

            await File.WriteAllTextAsync(filePath, updatedRoot.NormalizeWhitespace().ToFullString(), ct).ConfigureAwait(false);
            changed = true;
        }

        return changed;
    }

    public async Task<bool> ApplyTrailingNarrativeAfterClosingBraceFixAsync(
        string compileWorkspace,
        IReadOnlyList<BuildError> errors,
        CancellationToken ct)
    {
        var diagnosticReferences = CompileGateRepairDiagnostics.ResolveDiagnosticReferences(
            compileWorkspace,
            errors,
            CompileGateRepairPatterns.SyntaxNoiseCodes);
        if (diagnosticReferences.Count == 0)
        {
            return false;
        }

        var changed = false;
        foreach (var filePath in CompileGateRepairDiagnostics.EnumerateTargetCodeFiles(diagnosticReferences))
        {
            ct.ThrowIfCancellationRequested();
            var source = await File.ReadAllTextAsync(filePath, ct).ConfigureAwait(false);
            if (string.IsNullOrWhiteSpace(source))
            {
                continue;
            }

            if (!source.Contains("namespace ", StringComparison.Ordinal) &&
                !source.Contains(" class ", StringComparison.Ordinal) &&
                !source.Contains(" interface ", StringComparison.Ordinal) &&
                !source.Contains(" record ", StringComparison.Ordinal) &&
                !source.Contains(" struct ", StringComparison.Ordinal))
            {
                continue;
            }

            var lastBrace = source.LastIndexOf('}');
            if (lastBrace < 0 || lastBrace >= source.Length - 1)
            {
                continue;
            }

            var tail = source[(lastBrace + 1)..];
            if (string.IsNullOrWhiteSpace(tail))
            {
                continue;
            }

            var hasNarrativeMarkers =
                tail.IndexOf('`') >= 0 ||
                tail.Contains("In this transformation:", StringComparison.OrdinalIgnoreCase) ||
                tail.Contains("for demonstration purposes", StringComparison.OrdinalIgnoreCase) ||
                tail.Contains("Explanation:", StringComparison.OrdinalIgnoreCase) ||
                tail.Contains("Here is", StringComparison.OrdinalIgnoreCase) ||
                tail.Contains("Here's", StringComparison.OrdinalIgnoreCase) ||
                tail.Contains("This implementation", StringComparison.OrdinalIgnoreCase);
            if (!hasNarrativeMarkers)
            {
                continue;
            }

            var cleaned = source[..(lastBrace + 1)].TrimEnd() + Environment.NewLine;
            if (string.Equals(cleaned, source, StringComparison.Ordinal))
            {
                continue;
            }

            await File.WriteAllTextAsync(filePath, cleaned, ct).ConfigureAwait(false);
            changed = true;
        }

        return changed;
    }
}

