using Helper.Runtime.Core;

namespace Helper.Runtime.Generation;

internal sealed class TemplatePromotionVersionPlanner
{
    public async Task<string?> GetCurrentActiveVersionAsync(
        ITemplateLifecycleService lifecycle,
        string templateId,
        CancellationToken ct)
    {
        var versions = await lifecycle.GetVersionsAsync(templateId, ct);
        return versions.FirstOrDefault(x => x.IsActive)?.Version;
    }

    public async Task<string> ResolveNextVersionAsync(
        ITemplateLifecycleService lifecycle,
        string templatesRoot,
        string templateId,
        CancellationToken ct)
    {
        var versions = await lifecycle.GetVersionsAsync(templateId, ct);
        var parsed = new List<Version>();
        parsed.AddRange(versions.Select(v => ParseVersion(v.Version)).Where(v => v is not null).Select(v => v!));

        var candidatesRoot = Path.Combine(templatesRoot, templateId, "candidates");
        if (Directory.Exists(candidatesRoot))
        {
            foreach (var candidateDir in Directory.GetDirectories(candidatesRoot))
            {
                ct.ThrowIfCancellationRequested();
                var candidateVersion = Path.GetFileName(candidateDir);
                var parsedCandidate = ParseVersion(candidateVersion);
                if (parsedCandidate is not null)
                {
                    parsed.Add(parsedCandidate);
                }
            }
        }

        if (parsed.Count == 0)
        {
            return "1.0.0";
        }

        var latest = parsed.Max();
        if (latest is null)
        {
            return "1.0.0";
        }

        var nextPatch = latest.Build < 0 ? 0 : latest.Build + 1;
        return $"{latest.Major}.{latest.Minor}.{nextPatch}";
    }

    public string BuildAutoTemplateId(string prompt)
    {
        var tokens = prompt
            .Split(new[] { ' ', '\t', '\r', '\n', ',', '.', ':', ';', '!', '?' }, StringSplitOptions.RemoveEmptyEntries)
            .Select(KeepAlphaNumeric)
            .Where(x => !string.IsNullOrWhiteSpace(x))
            .Take(4)
            .ToList();

        if (tokens.Count == 0)
        {
            return "Template_AutoGenerated";
        }

        return $"Template_Auto_{string.Join("_", tokens)}";
    }

    private static Version? ParseVersion(string? raw)
    {
        if (string.IsNullOrWhiteSpace(raw))
        {
            return null;
        }

        var normalized = raw.Trim().TrimStart('v', 'V');
        return Version.TryParse(normalized, out var parsed) ? parsed : null;
    }

    private static string KeepAlphaNumeric(string token)
    {
        var chars = token.Where(char.IsLetterOrDigit).ToArray();
        return chars.Length == 0 ? string.Empty : new string(chars);
    }
}

