param(
    [string]$ApiBase = "http://localhost:5000",
    [string]$Output = "services/generatedOpenApiSummary.ts"
)

$ErrorActionPreference = "Stop"

$openApiUrl = "$ApiBase/api/openapi.json"
Write-Host "[ApiClientGen] Fetching $openApiUrl"
$spec = Invoke-RestMethod -Uri $openApiUrl -Method Get

$paths = $spec.paths.PSObject.Properties.Name | Sort-Object
$header = @"
// AUTO-GENERATED SUMMARY CLIENT
// Generated by scripts/generate_typed_client.ps1
import { API_ROOT, withApiHeaders } from './apiConfig';

export const generatedEndpoints = [
"@

$lines = $paths | ForEach-Object { "  '$($_)'," }
$footer = @"
];

export async function callGenerated(path: string, method: string = 'GET', body?: unknown) {
  const response = await fetch(`${API_ROOT}${path}`, {
    method,
    headers: withApiHeaders({
      ...(body ? { 'Content-Type': 'application/json' } : {})
    }),
    ...(body ? { body: JSON.stringify(body) } : {})
  });
  if (!response.ok) throw new Error(`API ${response.status}: ${path}`);
  return response.status === 204 ? null : await response.json();
}
"@

$content = ($header + "`r`n" + ($lines -join "`r`n") + "`r`n" + $footer)
Set-Content -Path $Output -Value $content -Encoding UTF8
Write-Host "[ApiClientGen] Generated $Output"
