using Helper.Api.Backend.ModelGateway;

namespace Helper.Api.Backend.Capabilities;

internal sealed record ModelCapabilityDefinition(
    HelperModelClass ModelClass,
    string RouteKey,
    string IntendedUse,
    string LatencyTier,
    bool SupportsStreaming,
    bool SupportsToolUse,
    bool SupportsVision,
    bool SupportsLongContext,
    bool SupportsDeepReasoning,
    bool SupportsVerification,
    string CostTier,
    int MaxSuggestedContextTokens,
    string FallbackClass,
    IReadOnlyList<string> Notes);

internal static class ModelCapabilityCatalogDefinitions
{
    public static IReadOnlyList<ModelCapabilityDefinition> All { get; } = new[]
    {
        new ModelCapabilityDefinition(
            HelperModelClass.Fast,
            "fast",
            "Low-latency general responses and fast fallback traffic.",
            "low",
            SupportsStreaming: true,
            SupportsToolUse: false,
            SupportsVision: false,
            SupportsLongContext: false,
            SupportsDeepReasoning: false,
            SupportsVerification: false,
            CostTier: "low",
            MaxSuggestedContextTokens: 6000,
            FallbackClass: "reasoning",
            Notes: new[] { "Primary low-latency route.", "Tool orchestration happens above the model gateway." }),
        new ModelCapabilityDefinition(
            HelperModelClass.Reasoning,
            "reasoning",
            "Long-form reasoning, grounded analysis, and complex synthesis.",
            "medium",
            SupportsStreaming: true,
            SupportsToolUse: false,
            SupportsVision: false,
            SupportsLongContext: true,
            SupportsDeepReasoning: true,
            SupportsVerification: false,
            CostTier: "medium",
            MaxSuggestedContextTokens: 32000,
            FallbackClass: "fast",
            Notes: new[] { "Default route for deeper analysis.", "May act as fallback for critic and vision workloads." }),
        new ModelCapabilityDefinition(
            HelperModelClass.Coder,
            "coder",
            "Code generation, repair, and build-oriented development tasks.",
            "medium",
            SupportsStreaming: true,
            SupportsToolUse: false,
            SupportsVision: false,
            SupportsLongContext: true,
            SupportsDeepReasoning: true,
            SupportsVerification: false,
            CostTier: "medium",
            MaxSuggestedContextTokens: 24000,
            FallbackClass: "reasoning",
            Notes: new[] { "Preferred for builder and generation flows." }),
        new ModelCapabilityDefinition(
            HelperModelClass.Vision,
            "vision",
            "Image-aware or multimodal interpretation tasks.",
            "high",
            SupportsStreaming: true,
            SupportsToolUse: false,
            SupportsVision: true,
            SupportsLongContext: false,
            SupportsDeepReasoning: true,
            SupportsVerification: false,
            CostTier: "high",
            MaxSuggestedContextTokens: 16000,
            FallbackClass: "reasoning",
            Notes: new[] { "Vision route availability depends on installed model catalog." }),
        new ModelCapabilityDefinition(
            HelperModelClass.Critic,
            "critic",
            "Review, critique, and verification passes.",
            "medium",
            SupportsStreaming: true,
            SupportsToolUse: false,
            SupportsVision: false,
            SupportsLongContext: false,
            SupportsDeepReasoning: true,
            SupportsVerification: true,
            CostTier: "medium",
            MaxSuggestedContextTokens: 12000,
            FallbackClass: "reasoning",
            Notes: new[] { "Uses configured critic fallback when present." }),
        new ModelCapabilityDefinition(
            HelperModelClass.Background,
            "background",
            "Lower-priority maintenance or background work.",
            "high",
            SupportsStreaming: false,
            SupportsToolUse: false,
            SupportsVision: false,
            SupportsLongContext: true,
            SupportsDeepReasoning: false,
            SupportsVerification: false,
            CostTier: "low",
            MaxSuggestedContextTokens: 12000,
            FallbackClass: "fast",
            Notes: new[] { "Runs through the background execution pool." }),
    };
}

